### PR TITLE
titiksha2k16

### PR DESCRIPTION
**Pull request by madanpandey97**
only titiksha2k16 contain all the necessary file

### CODE REVIEW

**Comment by mbj36** [comment]
@rishy Can u please suggest workflow to @madanpandey97  , Like new branch for 2016 etc and more about the changes :)

**Comment by rishy** [comment]
@smvdu/titiksha for branching and generic git hierarchy you guys can have a look at - http://nvie.com/posts/a-successful-git-branching-model/. In addition to that, these are the guidelines that I follow - https://github.com/rishy/sfd-smvdu/blob/develop/README.md#contribution-guidelines.

**Comment by Pulkit07** [comment]
@madanpandey97 can you break these commits into smaller commits, divide it into chunks because 329 file changes in just 4 commits defeats the purpose of using a vcs i.e. git and the platform github.

And one more thing, when you clone the existing repository, create a new branch and start working in that. So that we have previous year's website safe in another branch.

**Comment by shyam2tayal** [comment]
@madanpandey97  Following the previous year trends what you can do is .. checkout to branch named "old" , Copy all the master branch content there with a folder name Titiksha2015-16 .Then you can place your new code in master branch and then create pull request.
This will sustain code of all previous years and your working won't be hindered.

**Comment by Parbhat** [comment]
@rishy Following the trend, the existing website should be moved to `old` branch. Last year @shyam2tayal moved the website. @shyam2tayal it would be great if you can clean up things this year also.

**Comment by shyam2tayal** [comment]
@Parbhat  Sure sir , i will do it.

**Comment by shyam2tayal** [comment]
@Parbhat @madanpandey97  I have cleared both the master and develop branch. You can use both for your website making . Titiksha 15-16 shifted to old branch.

**Pull request merged**
